### ISSUE TITLE
Error: Using $this when not in object context (ObjectPositionExtension.php on line 39)

### ISSUE THREAD

**Issue by rcknr** [pix-digital/pixSortableBehaviorBundle#19]
I get this error when using the default template. PHP 5.3, Symfony 2.6.5.

**Comment by Hakadel** [comment]
I have the same error, any idea ? :up:

**Comment by nicolasricci** [comment]
any particular user case where you have the issue. I cannot manage to reproduce

**Comment by nicolasricci** [comment]
OK I have just noticed the __construct() method is not declared as public ... it is probably coming from there.
I will submit a patch now

**Comment by nicolasricci** [comment]
@Hakadel any better now?

**Comment by Hakadel** [comment]
@nicolasricci No same error after update... :(

**Comment by nicolasricci** [comment]
hmmm ok are you using php 5.3 as well? Are you using it a standalone module or within SonataAdmin?

**Comment by Hakadel** [comment]
I'm using PHP 5.3.10-1ubuntu3.18, with SonataAdmin

**Comment by nicolasricci** [comment]
ok this is a limitation of php 5.3 indeed.
@vvh-empora can you clarify why you require a twig function to get the object position? https://github.com/pix-digital/pixSortableBehaviorBundle/blob/cc7d50e9912b728f98e65d329dd80bc6e405ec71/Resources/views/Default/_sort.html.twig

@Hakadel in the meantime you can override the _sort.html.twig file and use the version from the v0.1 tag (https://github.com/pix-digital/pixSortableBehaviorBundle/blob/v0.1/Resources/views/Default/_sort.html.twig)

**Comment by nicolasricci** [comment]
@vvh-empora ok sorry I realised it was to get the correct method according to the position_field configuration. 
I will try to find another way to achieve this so it can remain compatible with php 5.3

**Comment by Hakadel** [comment]
@nicolasricci Even with the old _sort.html.twig it's not working... Because error is in ObjectPositionExtension.php

**Comment by nicolasricci** [comment]
the extension is only called by the `sortableObjectPosition` twig function so if you used the `_sort.html.twig` file I was referring to you should not have any problem.
Alternatively you can use the v0.1 tag which works fine

**Comment by OskarStark** [comment]
any news on this error?

@Hakadel is it working n the meantime?
