### ISSUE TITLE
bad order with move top and move bottom

### ISSUE THREAD

**Issue by aliocza** [pix-digital/pixSortableBehaviorBundle#22]
Hi,

The order of the list is incorrect when using the "move up" or "move down".

example move id 12 to first position : 
the order of the 2nd élèments should start at 1, not 2.  (id 11 and 10 has same position)
![bug](https://cloud.githubusercontent.com/assets/8338334/8649270/038ca97a-2969-11e5-9f25-a98b049315fc.jpg)

i use sonata admin and i config with : https://sonata-project.org/bundles/admin/master/doc/cookbook/recipe_sortable_listing.html

Can u help me ?

**Comment by OskarStark** [comment]
@aliocza i can't reproduce the problem, do still have these problems?

**Comment by aliocza** [comment]
My demo project :
http://www.renska.be/starterkit.rar

i have started with 'locale' entity into sonata admin :
StarterKit\CoreBundle\Entity
StarterKit\CoreBundle\Admin\LocaleAdmin.php
StarterKit\CoreBundle\Resources\config\admin.yml

**Comment by leto3087** [comment]
I have the same problem...

**Comment by crrash** [comment]
Same problem for me. Followed the documentation step by step...

**Comment by nicolasricci** [comment]
i am sorry but i really don't manage to reproduce. are you using the latest stable branch? I will double check the doc in case there is a typo but moving any item to first position is working well on various projects I am using the bundle on.

**Comment by OskarStark** [comment]
do you start with 0 or 1 for the first item as position?

**Comment by crrash** [comment]
I start with 0 for the first position. The version downloaded by composer is "pixassociates/sortable-behavior-bundle": "^0.3.0@dev".

**Comment by leto3087** [comment]
I use the dev-master version...

**Comment by p34c3m4k3r** [comment]
I am currently using "pixassociates/sortable-behavior-bundle": "^1.0", tried also with dev-master. Tried with first position 0 and first position 1. AND MOVE TOP/BOTTOM DIDN'T WORK ANYWAY! Please do something to fix it. It have to reorder all the other items between current position of the moved item and top/bottom position with +1 fro top and -1 for bottom.

**Comment by OskarStark** [comment]
@p34c3m4k3r no one will fix this for you!
This all is OpenSource, so if there is an you could fix it by yourself and create a Pull Request, or at least create an issue ticket where are detailed steps how to reproduce this issue

**Comment by aliocza** [comment]
I think I found the problem:
https://github.com/Atlantic18/DoctrineExtensions/issues/1130
https://github.com/Atlantic18/DoctrineExtensions/pull/908

But I have not yet found a solution ...
