### ISSUE TITLE
use font-awesome icons instead of utf-8 chars

### ISSUE THREAD

**Issue by OskarStark** [pix-digital/pixSortableBehaviorBundle#28]
What do you think?

i would prefer these ones:
<img width="1277" alt="bildschirmfoto 2015-09-18 um 21 29 07" src="https://cloud.githubusercontent.com/assets/995707/9969071/8b3dd96c-5e4c-11e5-9da8-961484507119.png">

@nicolasricci if you agree, i could provide a PR

**Comment by OskarStark** [comment]
you like it @nicolasricci ?

**Comment by dVaffection** [comment]
I second it. UTF-8 chars are not displayed properly 

![screen shot 2016-03-14 at 1 08 45 pm](https://cloud.githubusercontent.com/assets/457097/13758287/f0f830de-e9e5-11e5-92f5-ad76d124f421.png)

**Comment by nicolasricci** [comment]
@OskarStark @dVaffection OK to have a PR on this

**Comment by nicolasricci** [comment]
Fixed in PR #46
