### ISSUE TITLE
Pix\SortableBehaviorBundle\Resources/config\services.yml" does not contain valid YAML.

### ISSUE THREAD

**Issue by lucian0308** [pix-digital/pixSortableBehaviorBundle#40]
Caused by
Symfony\Component\Yaml\Exception\ParseException: The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at lin
e 21 (near "- @pix_sortable_behavior.position").

Use

```
- "@pix_sortable_behavior.position"
```
not

```
- @pix_sortable_behavior.position
```

**Comment by nicolasricci** [comment]
fixed in PR #42

**Comment by sethrea** [comment]
When will this be made part of a stable release?

**Comment by nicolasricci** [comment]
Branch 1.1 created

**Comment by sc0rp10** [comment]
@nicolasricci please tag release for Packagist installation without requiring dev packages.

**Comment by oservieres** [comment]
I agree, this would be really appreciated !
