### ISSUE TITLE
Warning: get_class() expects parameter 1 to be object, string given

### ISSUE THREAD

**Issue by xmon** [pix-digital/pixSortableBehaviorBundle#57]
I follow tutorial [SORTABLE BEHAVIOR IN ADMIN LISTING](https://sonata-project.org/bundles/admin/3-x/doc/cookbook/recipe_sortable_listing.html) but after Symfony update stopped working and throws an error.

```php
Warning: get_class() expects parameter 1 to be object, string given
500 Internal Server Error - ContextErrorException
```

1. in app/cache/dev/classes.php at line 6835
```php
}
public static function getClass($object)
{
return self::getRealClass(get_class($object));
}
public static function getParentClass($className)
{
```

2. at ErrorHandler ->handleError ('2', 'get_class() expects parameter 1 to be object, string given', '/var/www/virtual/domain.es/dev/htdocs/app/cache/dev/classes.php', '6835', array('object' => 'AppBundle\Entity\RedesSociales')) 
3. at get_class ('AppBundle\Entity\RedesSociales') in app/cache/dev/classes.php at line 6835   + 
4. at ClassUtils ::getClass ('AppBundle\Entity\RedesSociales') in vendor/pixassociates/sortable-behavior-bundle/Pix/SortableBehaviorBundle/Services/PositionORMHandler.php at line 48   + 
5. at PositionORMHandler ->getLastPosition ('AppBundle\Entity\RedesSociales')  in src/AppBundle/Admin/RedesSocialesAdmin.php at line 79   + 
6. at RedesSocialesAdmin ->configureListFields (object(ListMapper)) in app/cache/dev/classes.php at line 9832   + 
7. at Admin ->buildList () in app/cache/dev/classes.php at line 10420   + 
8. at Admin ->hasListFieldDescription ('sort') in app/cache/dev/classes.php at line 9878   + 
9. at Admin ->buildDatagrid () in app/cache/dev/classes.php at line 10201   + 
10. at Admin ->getDatagrid () in vendor/sonata-project/admin-bundle/Controller/CRUDController.php at line 216   + 
11. at CRUDController ->listAction () 
12. at call_user_func_array (array(object(SortableAdminController), 'listAction'), array()) in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 144   + 
13. at HttpKernel ->handleRaw (object(Request), '1') in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 64   + 
14. at HttpKernel ->handle (object(Request), '1', true) in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php at line 69   + 
15. at ContainerAwareHttpKernel ->handle (object(Request), '1', true) in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php at line 185   + 
16. at Kernel ->handle (object(Request)) in web/app_dev.php at line 30  

#### Symfony packages

symfony/assetic-bundle     v2.8.1  Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/phpunit-bridge     v2.8.16 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.3.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.3.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v2.8.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.4.2  Symfony SwiftmailerBundle
symfony/symfony            v2.8.16 The Symfony PHP framework

#### PHP version

PHP 5.4.45-0+deb7u2 (cli) (built: Oct 17 2015 08:26:31) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

Dumping here:
```php
dump($this->getRoot()->getClass());
$this->last_position = $this->positionService->getLastPosition($this->getRoot()->getClass());
```

I get:
```hash
"AppBundle\Entity\RedesSociales"
```

**Comment by xmon** [comment]
I solve it downgrade from 1.1 to 1.0 version. 

maybe a 1.1 bug?

**Comment by LaurentFl** [comment]
Hi, you can see my answer on [SonataAdminBundle Issue](https://github.com/sonata-project/SonataAdminBundle/issues/4299#issuecomment-276642050)

**Comment by xmon** [comment]
hi man, great!!
