### ISSUE TITLE
Discriminator with Class table inheritance not working correctly for getLastPosition

### ISSUE THREAD

**Issue by twify93** [pix-digital/pixSortableBehaviorBundle#60]
Hello,
I have this problem where I am using the setup with discriminator in Doctrine and the Class table inheritance and the field is actually on the main Entity rather than each individual Entity, because I want to sort them all on 1 place.
But this causes the problem that getLastPossition creates query for the child entity class rather than the main. And so I see them all in 1 page, but the buttons are all wrong, because of that.
Meaning that imageOnSide records are only 2 and that's why the getLastPossition returns 2, but it should count all elements in parent entity.

<img width="1441" alt="screen shot 2017-04-06 at 10 07 53" src="https://cloud.githubusercontent.com/assets/8925621/24744047/f252fc6e-1ab0-11e7-9c1a-f0901ca319f9.png">

**Comment by Tofandel** [comment]
I've made a fix for this issue in the PositionORMHandler.php file : 
```php
 public function getLastPosition($entity)
    {
	    $entityClass = ClassUtils::getClass($entity);
	    $parentEntityClass = true;
	    while ($parentEntityClass)
	    {
		    $parentEntityClass = ClassUtils::getParentClass($entity);
		    if ($parentEntityClass)
			    $entityClass = $parentEntityClass;
	    }

        $positionFields = $this->getPositionFieldByEntity($entityClass);
        $result = $this->dm
            ->createQueryBuilder($entityClass)
            ->hydrate(false)
            ->select($positionFields)
            ->sort($positionFields, 'desc')
            ->limit(1)
            ->getQuery()
            ->getSingleResult();

        if (is_array($result) && isset($result[$positionFields])) {
            return $result[$positionFields];
        }

        return 0;
    }
```

**Comment by foucdeg** [comment]
Hello @Tofandel, 

I've got the opposite situation and this patch broke my code :(
the position field is in my child class.
How can I work around this?

**Comment by filiplikavcan** [comment]
Checking parent (and excluding abstract parent) is clearly not enough for a use case where position field is in child class. It would be better if it is possible to define whether parent(s) should be investigated for position field. For example like this:

`# app/config/config.yml
pix_sortable_behavior:
    db_driver: mongodb # default value : orm
    position_field:
        default: sort #default value : position
        entities:
            AppBundle\Entity\Foobar: order # field is directly in this class
            AppBundle\Entity\Baz: parent.order # field is in a direct parent class
            AppBundle\Entity\Foo: AppBundle\Entity\FooGrandParent.order # field is in any ancestor class
    sortable_groups:
        entities:
            AppBundle\Entity\Baz: [ group ]`

**Comment by Tofandel** [comment]
It's been quite some time
But there is no need for this, a ReflectionClass/ReflectionProperty check to make sure the position field is there during the loop could do the trick..

**Comment by filiplikavcan** [comment]
That would be great. We had to downgrade to 1.3 on one of our project where we have parent entity which is not abstract. Both of the entities have position field so the Reflection solution would not help but we could at least adjust the parent class and rename the field.
