### ISSUE TITLE
Enable Drag'n drop feature

### ISSUE THREAD

**Issue by ceesvanegmond** [pix-digital/pixSortableBehaviorBundle#62]
Hello,

Maybe it's an idea to enable Drag'n Drop like feature? Instead of the ```up, down, top, bottom``` methods, it could be handy to say something like:

```Post``` with ID X to position X, instead of ```up, down etc```.

Is that an idea that we could implement and you will accept?

We could also offer another template with one action that enables drag'n drop (Maybe even include jQuery UI Sortable).

**Comment by ceesvanegmond** [comment]
@nicolasricci Could you respond on this?

**Comment by nicolasricci** [comment]
@ceesvanegmond sure i would be happy to review any new feature.

**Comment by ceesvanegmond** [comment]
@nicolasricci In that case, please check the pullrequest https://github.com/pix-digital/pixSortableBehaviorBundle/pull/63. Also it's good to review the other pullrequest https://github.com/pix-digital/pixSortableBehaviorBundle/pull/61

**Comment by Tofandel** [comment]
A bit of an issue with drag& drop with sortGroups, I'll send a PR
