### ISSUE TITLE
Why method getPosition() is required?

### ISSUE THREAD

**Issue by peter-gribanov** [pix-digital/pixSortableBehaviorBundle#69]
You are [required](https://github.com/pix-digital/pixSortableBehaviorBundle/blob/master/Services/PositionHandler.php#L100) method `getPosition()` if i use field `position` for sorting.
Is not good.

I use [DTO](https://en.wikipedia.org/wiki/Data_transfer_object) in SonataAdminBundle and the `position` property is public.
I'm forced to create a public method only for compatibility with your library.

Maybe need use something like [PropertyAccess](https://symfony.com/doc/current/components/property_access.html)? Or make your own [implementation](https://github.com/symfony/property-access/blob/master/PropertyAccessor.php#L437)?

**Comment by peter-gribanov** [comment]
The same [problem](https://github.com/pix-digital/pixSortableBehaviorBundle/blob/master/Controller/SortableAdminController.php#L56) with the `setPosition()` method.

**Comment by nicolasricci** [comment]
@peter-gribanov has been fixed

**Comment by peter-gribanov** [comment]
@nicolasricci sorry, but i do not see that this problem has been fixed.
Can you specify here a link to PR or commit?

**Comment by nicolasricci** [comment]
@peter-gribanov getter and setter are still required but the property name is now configurable (https://github.com/pix-digital/pixSortableBehaviorBundle/blob/master/README.md#configuration). I thought it was what you meant.
Feel free to make a PR to meet your needs and I will review it.
