### ISSUE TITLE
totally incorrect reordering

### ISSUE THREAD

**Issue by ivanbrykov** [pix-digital/pixSortableBehaviorBundle#81]
After playing with this bundle for a bit I ended up with the following picture:

![image](https://user-images.githubusercontent.com/476516/38219407-2526ca88-369b-11e8-9c0a-40738b6a85ad.png)

Here is how it looks in the DB:
![image](https://user-images.githubusercontent.com/476516/38219475-626fcaca-369b-11e8-9529-b29d5f36a44e.png)

Initially all items were ordered from 0 to 10. I clicked double arrows couple of times and now I have 3 items with order 10.

**Comment by mattchete** [comment]
I have the same problem, tried 1.3, 1.4, 1.5.
Have you found a solution ?

Thanks !

**Comment by brykov** [comment]
@mattchete our solution was to implement it from scratch using more simplistic approach. Sorry for the bad news.

**Comment by mattchete** [comment]
Ok, thanks for the answer

**Comment by BenjiBoy13** [comment]
@brykov, @mattchete  I just faced this error in my app, i fixed by myself too.

**Comment by ibasaw** [comment]
> @brykov, @mattchete I just faced this error in my app, I fixed it by myself too.

how ?

**Comment by AjbarAbdelmajid** [comment]
i'm facing the same problem. any solution found ???

**Comment by brykov** [comment]
> i'm facing the same problem. any solution found ???

We have implemented our own view. There is no workaround for this bug as far as I'm aware.

**Comment by AjbarAbdelmajid** [comment]
> > i'm facing the same problem. any solution found ???
> 
> We have implemented our own view. There is no workaround for this bug as far as I'm aware.

thanks for the reposnce. is there any other bundle that would do the job

**Comment by tonyellow** [comment]
Here exactly the same, completely incorrect ordering. Thinking of implementing it myself too if there is no other solution, anybody?

**Comment by AjbarAbdelmajid** [comment]
> Here exactly the same, completely incorrect ordering. Thinking of implementing it myself too if there is no other solution, anybody?

hi we had to override the pixsortablebehavior js that was responsible for firing events and redirect the js ajax to our custom made methods that took care of each entity that had the sorting . the code https://github.com/AjbarAbdelmajid/pixSortableBehaviorBundleCustomReorderingFix . feel free to update it and push back ;)

**Comment by dmitryuk** [comment]
Sonata admin officially migrated to `runroom-packages/sortable-behavior-bundle`, try it instead.
https://symfony.com/bundles/SonataAdminBundle/current/cookbook/recipe_sortable_listing.html
