### ISSUE TITLE
Error in the new symfony/config

### ISSUE THREAD

**Issue by iAdil** [pix-digital/pixSortableBehaviorBundle#94]
Please change it in the Configuration.php file

Pix\SortableBehaviorBundle\DependencyInjection\Configuration
```
        $treeBuilder = new TreeBuilder('pix_sortable_behavior');
        if (method_exists($treeBuilder, 'getRootNode')) {
            $rootNode = $treeBuilder->getRootNode();
        } else {
            // BC layer for symfony/config 4.1 and older
            $rootNode = $treeBuilder->root('pix_sortable_behavior');
        }

```
Without we will et an error:
`Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /app/vendor/pixassociates/sortable-behavior-bundle/Pix/SortableBehaviorBundle/DependencyInjection/Configuration.php on line 30 and at least 1 expected
`

**Comment by dmitryuk** [comment]
Sonata admin officially migrated to `runroom-packages/sortable-behavior-bundle`, try it instead.
https://symfony.com/bundles/SonataAdminBundle/current/cookbook/recipe_sortable_listing.html
